### PR TITLE
Add debian support and an extension.

### LINKED ISSUE #30: Support filter() expression
I tried to use filter() expression do to some replacement in files that are going to rpm, but it didn't work.
The code looked like that:

```
rpm {
    from('scripts') {
        into '/usr/local/myproduct/bin'
        filter({ line ->
            return line//line.replaceAll('{{BASE}}', '/usr/local/myproduct')
        })
    }
    ...
```

It threw an exception (caught using --stacktrace option):

```
Caused by: java.lang.UnsupportedOperationException
    at org.gradle.api.internal.file.copy.MappingCopySpecVisitor$FileVisitDetailsImpl.getFile(MappingCopySpecVisitor.java:85)
    at com.trigonic.gradle.plugins.rpm.RpmCopySpecVisitor.visitFile(RpmCopySpecVisitor.groovy:81)
    at org.gradle.api.internal.file.copy.NormalizingCopySpecVisitor.visitFile(NormalizingCopySpecVisitor.java:70)
    at org.gradle.api.internal.file.copy.MappingCopySpecVisitor.visitFile(MappingCopySpecVisitor.java:57)
    at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTree$1.visitFile(AbstractFileTree.java:145)
    at org.gradle.api.internal.file.collections.SingletonFileTree.visit(SingletonFileTree.java:40)
    at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:96)
    at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTree.visit(AbstractFileTree.java:136)
    at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:54)
    at org.gradle.api.internal.file.copy.CopyActionImpl.execute(CopyActionImpl.java:64)
    at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:42)
    at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:196)
    at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:102)
    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:99)
    at com.trigonic.gradle.plugins.rpm.Rpm_Decorated.invokeMethod(Unknown Source)
    at org.gradle.util.ReflectionUtil.invoke(ReflectionUtil.groovy:23)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$4.execute(AnnotationProcessingTaskFactory.java:150)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$4.execute(AnnotationProcessingTaskFactory.java:145)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:472)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:461)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:60)
    ... 57 more
```

It would be nice to support this standard in copy task function.

### PR DESCRIPTION
**Pull request by quidryan**
This is a biggy of a pull request, so let's talk about it. As a starter, it works, there's tests and it even fixes #30. There are two pieces of functionality added here: an extension and debian support.

The extension lets settings (like package name, requires, links) to be shared between all packaging tasks. It also provides a Copy spec which will be joined with the tasks. For instance, a copyright message could be copied into all rpm tasks, while also setting the os and arch for all tasks.

The debian support comes out of the pkg4j plugin, but is primarily supported by the jdeb library. There are  many similar conventions to redline.

Combined, they let you define a package just once via the extension, then get system packages for RedHat based and Debian based OS's, without losing the capabilities of either format. The .md files hopefully document the plugins in detail.

There's a few cleanups in here too, like no longer adding user/group/etc to every CopySpec's metaclass. Now it's confined to just our usages.

### CODE REVIEW

**Comment by quidryan** [comment]
The plugin might have to be renamed if this pull request is accepted. ;-)

**Comment by AlanKrueger** [comment]
You're right, this is a very large pull request.  I'll start reviewing the commits.  =)

~~Do you have any suggestions on a renamed plugin?  Something like the Gradle System Packaging Plugin?~~ Never mind, I see from the updated README.md you've picked "Gradle Linux Packaging Plugin". Is there anything that specifically limits this to Linux packaging?

**Comment by quidryan** [comment]
I'm very flexible on the name. My only thinking was Gradle System Packaging Plugin could make people think it works with Windows or OSX. Though, that'd be an interesting goal for the project. There is nothing specific to Linux. I'd go for Gradle System Packaging Plugin, then make some GitHub Issues to add OSX and Windows support later.

**Comment by quidryan** [comment]
Any other concerns or comments?

**Comment by AlanKrueger** [comment]
I just need to set aside some time to deal with this. Things have been a
bit hectic recently. :-)

**Comment by quidryan** [comment]
No problem, I completely understand, I've got my share of incoming pull requests on other projects. BTW, We're running with an internal build of this branch and it's working great.

**Comment by AlanKrueger** [comment]
Does yours work with Gradle 1.7? Looks like they've whacked some of the
internal classes I was obliged to leverage and the current Maven release
breaks.

**Comment by quidryan** [comment]
I saw that. It works with a 1.7 branch I use, but I have tried yet with the
final version. I'm out of the country for a few weeks and will take a look
when I get back at the end of the month.

**Comment by quidryan** [comment]
What happened to this merge? It's not in the tree anymore? Did someone force push over it?

**Comment by AlanKrueger** [comment]
That's on a separate branch at the moment since I was merging gradle 1.7
compatibility changes onto the master. There was a fair amount of outcry
for those.

**Comment by quidryan** [comment]
Ah, I see it, thanks. I'll start on merging the 1.7 stuff over, there seems to be few more changes than what was needed for the old stuff.

**Comment by quidryan** [comment]
I created another branch called add-debian-support-with-1.7 which has all the recent chances merged in. I'll create a pull request once I fix all the tests. There seems to be an issue with the CopySpecEnhancement's that act like property setters, in 1.7.

**Pull request merged**
