### PR TITLE
issue #40 - Prefixes/Relocatable RPM header support

### PR DESCRIPTION
**Pull request by otrosien**
https://github.com/TrigonicSolutions/gradle-rpm-plugin/issues/40

### CODE REVIEW

**Comment by AlanKrueger** [comment]
Can you add a unit test for the new functionality?

**Comment by AlanKrueger** [comment]
This has been deployed to Sonatype OSS snapshots as 1.5-SNAPSHOT https://oss.sonatype.org/content/repositories/snapshots/

**Comment by otrosien** [comment]
Look at the pull request, it is tested as part of RpmPluginTest. What else is there to test?

**Comment by otrosien** [comment]
This has become a duplicate of pull request #53, which is merged. So I'm closing it.

**Pull request closed without merging**
